Repository QuickSwap/interface-v2, pull requests merged in 2022-02, with the labels that each got.

#71 Fix issues in inputs
  src/assets/tokenLogo/0x4e78011ce80ee02d2c3e649fb657e45898257815.webp
  src/assets/tokenLogo/0x5ceebb0947d58fabde2fc026ffe4b33ccfe1ba8b.webp
  src/assets/tokenLogo/0x7cb810ecbfd6125e65f451cfbd8ae657dffdd6b4.webp
  src/assets/tokenLogo/0x91c89a94567980f0e9723b487b0bed586ee96aa7.webp
  src/assets/tokenLogo/0xa3c322ad15218fbfaed26ba7f616249f7705d945.webp
  src/assets/tokenLogo/0xb25e20de2f2ebb4cffd4d16a55c7b395e8a94762.webp
  src/assets/tokenLogo/0xcfb54a6d2da14abecd231174fc5735b4436965d8.webp
  src/assets/tokenLogo/0xdd2af2e723547088d3846841fbdcc6a8093313d6.webp
  src/assets/tokenLogo/0xe20d2df5041f8ed06976846470f727295cdd4d23.webp
  src/assets/tokenLogo/0xe40d881cf66e1f6d19979a5ff6c830c6af65d278.png
  src/components/CurrencyInput/CurrencyInput.tsx
  src/components/FarmDualCard/FarmDualCardDetails.tsx
  src/components/FarmLPCard/FarmLPCardDetails.tsx
  src/components/NumericalInput/NumericalInput.tsx
  src/components/NumericalInput/index.ts
  src/components/RemoveLiquidityModal/RemoveLiquidityModal.tsx
  src/components/SettingsModal/SettingsModal.tsx
  src/components/StakeQuickModal/StakeQuickModal.tsx
  src/components/StakeSyrupModal/StakeSyrupModal.tsx
  src/components/Swap/Swap.tsx
  src/components/UnstakeQuickModal/UnstakeQuickModal.tsx
  src/components/index.ts
  src/constants/index.ts
  src/constants/lists.ts
  src/constants/stake.json
  src/constants/tokens.json
  src/utils/index.ts
Labels: bug

#70 fix: add background as fallback when switch tabs to avoid blank screen
  src/App.tsx
  src/components/ToggleSwitch/ToggleSwitch.tsx
  src/layouts/Background.tsx
  src/layouts/PageLayout.tsx
Labels: bug, enhancement

#69 refactor: Improve scroll event lag
  src/components/CurrencySearchModal/CurrencyRow.tsx
  src/pages/DragonPage/DragonsSyrup.tsx
  src/pages/FarmPage/FarmPage.tsx
  src/utils/useInfiniteLoading.ts
Labels: enhancement

#74 Update inputs and pool card
  src/components/AddressInput/AddressInput.tsx
  src/components/AddressInput/index.ts
  src/components/PoolPositionCard/PoolPositionCard.tsx
  src/components/PoolPositionCard/PoolPositionCardDetails.tsx
  src/components/SettingsModal/SettingsModal.tsx
  src/components/Swap/Swap.tsx
  src/components/index.ts
Labels: enhancement, Passed PR Review

#73 fix: show loading indicator on farm and dragon lair page
  src/pages/DragonPage/DragonsSyrup.tsx
  src/pages/FarmPage/FarmPage.tsx
Labels: enhancement, Passed PR Review

#68 Update farm/dragons page
  src/components/CustomSwitch/CustomSwitch.tsx
  src/components/CustomSwitch/index.ts
  src/components/FarmDualCard/FarmDualCard.tsx
  src/components/FarmDualCard/FarmDualCardDetails.tsx
  src/components/FarmLPCard/FarmLPCard.tsx
  src/components/FarmLPCard/FarmLPCardDetails.tsx
  src/components/SwapTokenDetails/SwapTokenDetails.tsx
  src/components/SyrupCard/SyrupAPR.tsx
  src/components/SyrupCard/SyrupCard.tsx
  src/components/SyrupCard/SyrupCardDetails.tsx
  src/components/SyrupCard/SyrupTimerLabel.tsx
  src/components/index.ts
  src/pages/DragonPage/DragonsSyrup.tsx
  src/pages/FarmPage/FarmPage.tsx
  src/pages/FarmPage/FarmsList.tsx
  src/utils/index.ts
Labels: enhancement

#77 Fix frontend issues
  src/components/StakeSyrupModal/StakeSyrupModal.tsx
  src/components/SyrupCard/SyrupCardDetails.tsx
Labels: Passed PR Review

#78 Fix Typo with DragonsLair
  src/components/Header/Header.tsx
  src/pages/DragonPage/DragonPage.tsx
  src/pages/LandingPage/LandingPage.tsx
Labels: bug, Passed PR Review

#82 Fix issue for dragons syrup
  src/components/StakeSyrupModal/StakeSyrupModal.tsx
  src/state/stake/hooks.ts
Labels: bug, Review Comments And Pass

#79 Fix some issues
  src/components/AddLiquidity/AddLiquidity.tsx
  src/components/Header/Header.tsx
  src/components/Swap/Swap.tsx
  src/components/WalletModal/WalletModal.tsx
  src/pages/LandingPage/LandingPage.tsx
  src/utils/index.ts
Labels: bug, Passed PR Review

#75 farm page performance improvements
  src/pages/DragonPage/DragonsSyrup.tsx
  src/pages/FarmPage/FarmsList.tsx
  src/utils/index.ts
Labels: enhancement, Review Comments And Pass

#84 Fix wallet connect on mobile.
  src/components/AddLiquidity/AddLiquidity.tsx
  src/components/BetaWarningBanner/BetaWarningBanner.tsx
  src/components/Header/Header.tsx
  src/components/Swap/Swap.tsx
  src/pages/LandingPage/LandingPage.tsx
  src/utils/index.ts
Labels: bug, Passed PR Review

#89 Rebase dev from master
  src/components/FarmDualCard/FarmDualCard.tsx
  src/components/FarmDualCard/FarmDualCardDetails.tsx
  src/components/FarmLPCard/FarmLPCard.tsx
  src/components/FarmLPCard/FarmLPCardDetails.tsx
  src/components/RewardSlider/RewardSliderItem.tsx
  src/constants/stake.json
  src/pages/FarmPage/FarmsList.tsx
  src/service-worker.ts
  src/state/stake/hooks.ts
  src/utils/index.ts
  src/utils/useInfiniteLoading.ts
  src/utils/useUSDCPrice.ts
Labels: Passed PR Review

#87 change copyright to 2022
  src/components/Footer/Footer.tsx
Labels: Passed PR Review

#83 Investigate a better way to calculate daily volume
  src/apollo/queries.ts
  src/state/stake/hooks.ts
  src/utils/index.ts
Labels: enhancement, Passed PR Review

#90 Update dragons page
  src/assets/images/AlertIcon.svg
  src/assets/images/DragonBg1.svg
  src/assets/images/DragonBg2.svg
  src/pages/DragonPage/DragonAlert.tsx
  src/pages/DragonPage/DragonPage.tsx
  src/pages/DragonPage/DragonsLair.tsx
Labels: enhancement, Review Comments And Pass

#88 Update landing page
  .env
  .env.production
  src/components/CustomModal/CustomModal.tsx
  src/components/MoonpayModal/MoonpayModal.tsx
  src/components/MoonpayModal/index.ts
  src/components/SyrupCard/SyrupAPR.tsx
  src/components/SyrupCard/SyrupCard.tsx
  src/components/SyrupCard/SyrupCardDetails.tsx
  src/components/index.ts
  src/constants/index.ts
  src/hooks/index.ts
  src/pages/DragonPage/DragonsLair.tsx
  src/pages/DragonPage/DragonsSyrup.tsx
  src/pages/LandingPage/BuyFiatSection.tsx
  src/pages/LandingPage/HeroSection.tsx
  src/pages/LandingPage/LandingPage.tsx
  src/pages/LandingPage/SwapSection.tsx
  src/pages/LandingPage/TradingInfo.tsx
  src/state/stake/hooks.ts
  src/utils/index.ts
Labels: enhancement, Review Comments And Pass

#93 Fix logo and update modal for buy fiat section
  src/assets/images/HelpIcon2.svg
  src/assets/images/Moonpay.svg
  src/assets/images/Transak.png
  src/assets/images/quickLogo.png
  src/assets/images/quickLogo.svg
  src/assets/tokenLogo/0x1599fe55cda767b1f631ee7d414b41f5d6de393d.png
  src/assets/tokenLogo/0x64875aaa68d1d5521666c67d692ee0b926b08b2f.png
  src/assets/tokenLogo/0x9bd9ad490dd3a52f096d229af4483b94d63be618.png
  src/assets/tokenLogo/0xfe4546fefe124f30788c4cc1bb9aa6907a7987f9.png
  src/components/BuyFiatModal/BuyFiatModal.tsx
  src/components/BuyFiatModal/index.ts
  src/components/Header/Header.tsx
  src/components/index.ts
  src/constants/index.ts
  src/constants/lists.ts
  src/constants/tokens.json
  src/pages/LandingPage/BuyFiatSection.tsx
Labels: bug, enhancement

#92 fix issues on frontend
  public/locales/en.json
  src/assets/tokenLogo/0x02649c1ff4296038de4b9ba8f491b42b940a8252.webp
  src/assets/tokenLogo/0x1659ffb2d40dfb1671ac226a0d9dcc95a774521a.webp
  src/assets/tokenLogo/0x2bc07124d8dac638e290f401046ad584546bc47b.webp
  src/assets/tokenLogo/0x4287f07cbe6954f9f0decd91d0705c926d8d03a4.png
  src/assets/tokenLogo/0x8d520c8e66091cfd6743fe37fbe3a09505616c4b.webp
  src/assets/tokenLogo/0xa863246658dea34111c3c1dcedb2cfd5d6067334.webp
  src/assets/tokenLogo/0xd5d86fc8d5c0ea1ac1ac5dfab6e529c9967a45e9.webp
  src/assets/tokenLogo/0xe8a05e85883f9663b18a38d7aa89853deaba56e3.webp
  src/components/PoolPositionCard/PoolPositionCard.tsx
  src/components/Swap/AdvancedSwapDetails.tsx
  src/components/Swap/SwapRoute.tsx
  src/components/SwapTokenDetails/SwapTokenDetails.tsx
  src/components/TransactionsTable/TransactionsTable.tsx
  src/constants/index.ts
  src/constants/lists.ts
  src/constants/stake.json
  src/constants/tokens.json
  src/pages/AnalyticsPage/AnalyticsHeader.tsx
  src/pages/AnalyticsPairDetails/AnalyticsPairDetails.tsx
  src/pages/DragonPage/DragonsSyrup.tsx
  src/pages/FarmPage/FarmsList.tsx
  src/pages/LandingPage/LandingPage.tsx
  src/state/application/actions.ts
  src/state/application/hooks.ts
  src/state/application/reducer.ts
  src/utils/index.ts
Labels: bug, Review Comments And Pass

#96 Fix rounding issue for token amounts in all pages
  public/locales/en.json
  src/components/AddLiquidity/AddLiquidity.tsx
  src/components/AddLiquidity/ConfirmAddModalBottom.tsx
  src/components/AddLiquidity/index.ts
  src/components/ConfirmSwapModal/ConfirmSwapModal.tsx
  src/components/ConfirmSwapModal/SwapModalHeader.tsx
  src/components/CurrencyInput/CurrencyInput.tsx
  src/components/CurrencySearchModal/CurrencyRow.tsx
  src/components/FarmCard/FarmCard.tsx
  src/components/FarmCard/FarmCardDetails.tsx
  src/components/FarmCard/index.ts
  src/components/FarmDualCard/FarmDualCardDetails.tsx
  src/components/FarmDualCard/index.ts
  src/components/FarmLPCard/FarmLPCard.tsx
  src/components/FarmLPCard/index.ts
  src/components/PoolPositionCard/PoolPositionCard.tsx
  src/components/PoolPositionCard/PoolPositionCardDetails.tsx
  src/components/PositionCard/PositionCard.tsx
  src/components/RemoveLiquidityModal/RemoveLiquidityModal.tsx
  src/components/RewardSlider/RewardSliderItem.tsx
  src/components/StakeQuickModal/StakeQuickModal.tsx
  src/components/StakeSyrupModal/StakeSyrupModal.tsx
  src/components/Swap/AdvancedSwapDetails.tsx
  src/components/Swap/Swap.tsx
  src/components/Swap/SwapRoute.tsx
  src/components/SyrupCard/SyrupCard.tsx
  src/components/SyrupCard/SyrupCardDetails.tsx
  src/components/UnstakeQuickModal/UnstakeQuickModal.tsx
  src/components/index.ts
  src/hooks/useSwapCallback.ts
  src/hooks/useWrapCallback.ts
  src/pages/DragonPage/DragonsLair.tsx
  src/pages/DragonPage/DragonsSyrup.tsx
  src/pages/FarmPage/FarmsList.tsx
  src/state/claim/hooks.ts
  src/state/stake/hooks.ts
  src/utils/index.ts
Labels: bug, Review Comments And Pass

#104 add new syrups and pools
  src/constants/stake.json
  src/utils/useUSDCPrice.ts
Labels: Passed PR Review

#105 Fix alpha site and add new syrups
  src/assets/tokenLogo/0x02649c1ff4296038de4b9ba8f491b42b940a8252.webp
  src/assets/tokenLogo/0x1599fe55cda767b1f631ee7d414b41f5d6de393d.png
  src/assets/tokenLogo/0x1659ffb2d40dfb1671ac226a0d9dcc95a774521a.webp
  src/assets/tokenLogo/0x2bc07124d8dac638e290f401046ad584546bc47b.webp
  src/assets/tokenLogo/0x4287f07cbe6954f9f0decd91d0705c926d8d03a4.png
  src/assets/tokenLogo/0x64875aaa68d1d5521666c67d692ee0b926b08b2f.png
  src/assets/tokenLogo/0x8d520c8e66091cfd6743fe37fbe3a09505616c4b.webp
  src/assets/tokenLogo/0x9bd9ad490dd3a52f096d229af4483b94d63be618.png
  src/assets/tokenLogo/0xa863246658dea34111c3c1dcedb2cfd5d6067334.webp
  src/assets/tokenLogo/0xd5d86fc8d5c0ea1ac1ac5dfab6e529c9967a45e9.webp
  src/assets/tokenLogo/0xe8a05e85883f9663b18a38d7aa89853deaba56e3.webp
  src/assets/tokenLogo/0xfe4546fefe124f30788c4cc1bb9aa6907a7987f9.png
  src/constants/stake.json
  src/constants/tokens.json
Labels: bug
