Repository QuickSwap/interface-v2, pull requests merged in 2022-03, with the labels that each got.

#107 Add new syrups and remove ended LP farms
  src/assets/tokenLogo/0x1eba4b44c4f8cc2695347c6a78f0b7a002d26413.webp
  src/assets/tokenLogo/0x3ad707da309f3845cd602059901e39c4dcd66473.webp
  src/assets/tokenLogo/0x7f280dac515121dcda3eac69eb4c13a52392cace.webp
  src/assets/tokenLogo/0x9cd6746665d9557e1b9a775819625711d0693439.webp
  src/assets/tokenLogo/0xe52509181feb30eb4979e29ec70d50fd5c44d590.webp
  src/assets/tokenLogo/0xf915fdda4c882731c0456a4214548cd13a822886.webp
  src/constants/index.ts
  src/constants/lists.ts
  src/constants/stake.json
  src/constants/tokens.json
Labels: Review Comments And Pass

#109 Update hooks for farms/syrups
  src/components/FarmCard/FarmCard.tsx
  src/components/FarmCard/FarmCardDetails.tsx
  src/components/RewardSlider/RewardSlider.tsx
  src/components/RewardSlider/RewardSliderItem.tsx
  src/components/StakeSyrupModal/StakeSyrupModal.tsx
  src/components/SyrupCard/SyrupAPR.tsx
  src/components/SyrupCard/SyrupCard.tsx
  src/components/SyrupCard/SyrupCardDetails.tsx
  src/pages/DragonPage/DragonsSyrup.tsx
  src/pages/FarmPage/FarmsList.tsx
  src/state/multicall/hooks.ts
  src/state/stake/hooks.ts
  src/types/index.ts
  src/utils/index.ts
Labels: enhancement, Review Comments And Pass

#112 Add new syrups
  src/constants/stake.json
Labels: Review Comments And Pass

#110 update @gelatonetwork/limit-orders-react and its dependencies
  package-lock.json
  package.json
  yarn.lock
Labels: Passed PR Review

#119 Add blockwallet support
  src/assets/images/blockwalletIcon.svg
  src/components/AccountDetails/AccountDetails.tsx
  src/components/AccountDetails/StatusIcon.tsx
  src/components/WalletModal/PendingView.tsx
  src/components/WalletModal/WalletModal.tsx
  src/constants/index.ts
Labels: Passed PR Review

#124 Update blank links and packages for audit
  package.json
  src/components/AccountDetails/AccountDetails.tsx
  src/components/AccountDetails/Transaction.tsx
  src/components/AddressInput/AddressInput.tsx
  src/components/AreaChart/AreaChart.tsx
  src/components/CurrencySearchModal/ListSelect.tsx
  src/components/Popups/TransactionPopup.tsx
  src/components/PositionCard/PositionCard.tsx
  src/components/SwapTokenDetails/SwapTokenDetails.tsx
  src/components/TransactionConfirmationModal/TransactionConfirmationModal.tsx
  src/components/TransactionsTable/TransactionsTable.tsx
  src/components/WalletModal/Option.tsx
  src/components/WalletModal/WalletModal.tsx
  src/pages/AnalyticsPairDetails/AnalyticsPairDetails.tsx
  src/pages/AnalyticsTokenDetails/AnalyticsTokenDetails.tsx
  src/pages/LandingPage/LandingPage.tsx
  yarn.lock
Labels: Passed PR Review

#123 Update packages and fix blank links for audit
  package.json
  src/components/AccountDetails/AccountDetails.tsx
  src/components/AccountDetails/Transaction.tsx
  src/components/AddressInput/AddressInput.tsx
  src/components/AreaChart/AreaChart.tsx
  src/components/CurrencySearchModal/ListSelect.tsx
  src/components/Popups/TransactionPopup.tsx
  src/components/PositionCard/PositionCard.tsx
  src/components/SwapTokenDetails/SwapTokenDetails.tsx
  src/components/TransactionConfirmationModal/TransactionConfirmationModal.tsx
  src/components/TransactionsTable/TransactionsTable.tsx
  src/components/WalletModal/Option.tsx
  src/components/WalletModal/WalletModal.tsx
  src/pages/AnalyticsPairDetails/AnalyticsPairDetails.tsx
  src/pages/AnalyticsTokenDetails/AnalyticsTokenDetails.tsx
  src/pages/LandingPage/LandingPage.tsx
  yarn.lock
Labels: Review Comments And Pass
